### ISSUE TITLE
Migration vers OWSLib 0.16.0

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mdchecker#32]
J'ai récemment imposé les versions des modules Python utilisés par mdchecker.
cf. https://github.com/geobretagne/mdchecker/commit/4a988d35726d93b78feb8c6b77fa12cac20d5811
En effet, la dernière version d'OWSLib s'avère incompatible avec mdchecker.
OWSLib 0.13.0 fonctionne.
OWSLib 0.16.0 ne fonctionne plus.

Certaines métadonnées lèvent des exceptions au niveau d'OWSLib :

```
[2018-07-23 09:37:05,694] ERROR in app: Exception on /quick_test/ [GET]
Traceback (most recent call last):
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/app/mdchecker/main.py", line 510, in quick_test
    metadatas, count, score = ins_wrapper.run_unrecorded_tests()
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/app/mdchecker/main.py", line 290, in run_unrecorded_tests
    maxharvest=self.test_params["maxharvest"]
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/app/mdchecker/inspirobot/Inspirobot.py", line 243, in mdsearch
    maxrecords=maxrecords, outputschema=self.OUTPUTSCHEMA)
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/owslib/csw.py", line 399, in getrecords2
    self._parserecords(outputschema, esn)
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/owslib/csw.py", line 549, in _parserecords
    self.records[identifier] = MD_Metadata(i)
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/owslib/iso.py", line 146, in __init__
    self.contentinfo.append(MD_FeatureCatalogueDescription(contentinfo))
  File "/Users/benji/dev/projects_current/mdchecker/mdchecker/venv/lib/python2.7/site-packages/owslib/iso.py", line 961, in __init__
    val = i.attrib['uuidref']
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70073)
KeyError: 'uuidref'
```

Exemple de requête produisant cela :
quick_test/?nextrecord=118&anytext=&cat=GéoBretagne&maxharvest=1

Migration vers OWSLib 0.16.0 à étudier...

**Comment by bchartier** [comment]
J'ai détaillé le souci là :
https://github.com/geopython/OWSLib/issues/491

**Comment by MaelREBOUX** [comment]
Oups : nous sommes maintenant à la versions 0.24.1

https://github.com/geopython/OWSLib/releases/tag/0.24.1
